bootstrap.servers=kafka:9092
key.serializer=org.apache.kafka.common.serialization.StringSerializer
value.serializer=org.apache.kafka.common.serialization.StringSerializer
acks=all
enable.idempotence=true
retries=5
max.in.flight.requests.per.connection=5
compression.type=snappy
linger.ms=10
